logging:
  level: INFO
  loggers:
    "org.eclipse.jetty": INFO
    "io.swagger": INFO
    "org.apache.kafka.clients.consumer.internals": WARN
    # Part of the default config and warns if can't find any file, normal most of the time
    "com.netflix.config.sources.URLConfigurationSource": OFF
    # Spams every time it polls dynamodb
    "com.netflix.config.sources.DynamoDbConfigurationSource": WARN
    # Spams when using default formatter for toString().
    "org.javamoney.moneta.Money": WARN
  appenders:
    - type: console

server:
  type: pleo
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  requestLog:
    appenders:
      - type: console
        filterFactories:
          - type: health-and-metrics-filter-factory
        layout:
          type: access-json
          timestampFormat: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"